activation_config:
  bit_width: 1
  narrow_range: False
  quant_type: 'QuantType.INT'
  scaling_impl_type: 'STATS'
  scaling_stats_op: 'MAX'
  scaling_min_val: null
weight_config:
  weight_bit_width : 1
  weight_quant_type : 'QuantType.BINARY'
  weight_narrow_range : False
  weight_scaling_impl_type : 'STATS'
  weight_scaling_stats_op : 'MAX'
  weight_scaling_min_val : null
